apiVersion: v1
kind: Service
metadata:
  name: app1-httpd-service
  namespace: default
  labels:
    name: app1-httpd
spec:
  type: NodePort
  selector:
    app: app1-httpd
  ports:
    - port: 80
      nodePort: 30080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-httpd-deploy
  namespace: default
  labels:
    app: app1-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-httpd
  template:
    metadata:
      labels:
        app: app1-httpd
    spec:
      containers:
      - name: app1-httpd
        image: 817521490787.dkr.ecr.us-east-1.amazonaws.com/raogaru-ecr:app1-httpd
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
#      imagePullSecrets:
#          - name: regcred
