Vagrant.configure("2") do |config|
      config.vm.box = "generic/rhel7"
      config.vm.provision "shell", inline: "echo redhat7 ready"
end

servers=[
 { :hostname => "redhat7", :vmip => "192.168.56.101"}
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "generic/rhel7"
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:vmip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", 1024]
		vb.name = machine[:hostname]
            end
#	    node.vm.provision :shell, path: "bootstrap.sh"
        end
    end
end

