# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

servers=[
 { :hostname => "postgres17", :vmip => "192.168.56.117"}
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "bento/amazonlinux-2"
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:vmip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", 1024]
		vb.name = machine[:hostname]
            end
	    node.vm.provision :shell, path: "bootstrap.sh"
        end
    end
end

