Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", 4096]
		vb.name = "win10"
  end
end
