# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

servers=[
 { :hostname => "nginx1", :vmip => "192.168.56.41", :port80 => 8041},
 { :hostname => "nginx2", :vmip => "192.168.56.42", :port80 => 8042}
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "bento/amazonlinux-2"
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:vmip]
            node.vm.network "forwarded_port", guest: 80, host: machine[:port80]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", 512]
		vb.name = machine[:hostname]
            end
	    node.vm.provision :shell, path: "bootstrap.sh"
        end
    end
end

