Vagrant.configure("2") do |config|
  config.vm.box = "fedora/37-cloud-base"
  config.vm.box_version = "37.20221105.0"
            config.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", 4096]
                vb.name = "Fedora-AWS-SCT"
            end

end
