pipeline {
    agent any
    stages {
        stage("stage 1 git scm") {
            steps {
                git branch: 'main',
                    credentialsId: 'raogaru-github',
                    url: 'git@github.com:raogaru/project.git'
            }
        }
        stage("stage 2 build docker image") {
            steps {
                // sh "pwd"
                // sh "find . -print"
                // sh "ls"
                sh "cd app1-httpd; docker build -t app1-httpd ."
                sh """
                    IMAGE_ID=\$(docker images app1-httpd --quiet)
                    echo \$IMAGE_ID
                    ECR_TOKEN=\$(aws ecr get-login-password --region us-east-1)
                    echo \$ECR_TOKEN | docker login --username AWS --password-stdin \$AWS_ECR_URL
                    docker tag \$IMAGE_ID \$AWS_ECR_REPO_NAME:app1-httpd
                    docker push \$AWS_ECR_REPO_NAME:app1-httpd
                    aws ecr list-images --region us-east-1 --repository-name raogaru-ecr
                """
            }
        }
    }
}
