pipeline {
    agent any
    stages {
        stage("stage 1 git scm") {
            steps {
                git branch: 'main',
                    credentialsId: 'raogaru-github',
                    url: 'git@github.com:raogaru/project.git'
            }
        }
        stage("stage 2 build/push/run docker image") {
            steps {
                // sh "pwd"
                // sh "find . -print"
                // sh "ls"
                sh """
                    APP_NAME=\${APP1_NAME}

                    echo \${APP_NAME}
                    cd \${APP_NAME}
                    echo "cd'd into folder"
                    docker build -t \${APP_NAME} .
                    echo "built"
                    IMAGE_ID=\$(docker images \${APP_NAME} --quiet)
                    echo \${IMAGE_ID}
                    ECR_TOKEN=\$(aws ecr get-login-password --region us-east-1)
                    echo \${ECR_TOKEN} | docker login --username AWS --password-stdin \$AWS_ECR_URL
                    docker tag \${IMAGE_ID} \${AWS_ECR_REPO_NAME}:\${APP_NAME}
                    docker push \${AWS_ECR_REPO_NAME}:\${APP_NAME}
                    aws ecr list-images --region us-east-1 --repository-name raogaru-ecr
                    
                    aws eks update-kubeconfig --region \${AWS_DEFAULT_REGION} --name \${AWS_EKS_CLUSTER_NAME}
                    kubectl get svc
                    
                    kubectl config get-contexts
                    kubectl config current-context
                    kubectl config use-context \${AWS_EKS_ARN}
                    kubectl config get-contexts
                    kubectl config current-context
                    kubectl explain pods
                    
                    kubectl get namespace
                    
                    kubectl get deployment
                    kubectl apply -f \${APP_NAME}.yaml
                    
                    kubectl get deploy
                    kubectl get svc
                    kubectl get pods
                """
            }
        }
    }
}
