Vagrant.configure("2") do |config|
  config.vm.box = "bento/amazonlinux-2"
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", 512]
     vb.name = "sandbox"
  end
end
